# Dropbox Configuration
refresh_token=X8Ogs3jedLAAAAAAAAAAAdX899MydSQM8e_-5P5Z60lliQR4iJXRxl81YUmkc4oX
client_id=kwps3743vkv4xqp
client_secret=znr5vz3i6myjixw

# アプリ初期値
task_name_default=中央区公園及び街路樹等総合維持管理業務\n(中部地区)
jv_name_default=南香・高重・蔵田 特定JV

# スピナーの中身 (カンマ区切り)
spinner_location=　,北５条線,北４条線,北３条線,北２条線,北１条線,北大通線,南大通線,西２０丁目線,西２１丁目線,西２３丁目線,西２４丁目線,西２５丁目線
spinner_route=　,あかしあ公園,山麓公園,どんぐり公園,日新公園,やちだも公園,さくらんぼ公園,北円山公園,北４条かすみ公園,南7条りんりん公園,南１０条明星公園,北４条まどか公園,円山裏参道公園,南６条西２２丁目広場,南１条西１８丁目広場,南２条みゆき公園,南１４条あゆみ公園
